plugins {
    id 'com.android.library'
}
android {
    namespace 'io.github.sckzw.aaosvehicleproperty.shared'
    compileSdk 37

    defaultConfig {
        minSdk 33
        targetSdk 37

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    // Add this to access android.car APIs
    useLibrary 'android.car'
}
dependencies {
    implementation libs.androidx.app
}